name: irmin-server

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.12.0
          - 4.11.0
          - 4.09.1
          - 4.08.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: git submodule update --init
      - run: opam pin add irmin-server.dev . --no-action
      - run: opam depext irmin-server --yes --with-doc
      - run: opam install irmin-server --deps-only --with-doc --with-test
      - run: opam exec -- dune build -p tezos-context-hash,irmin-server
      - run: opam exec -- dune runtest -p tezos-context-hash,irmin-server

  build-bench:
    strategy:
      fail-fast: true
      matrix:
        os:
          #- macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.12.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: git submodule update --init
      - run: opam pin add irmin-server.dev . --no-action
      - run: opam pin add irmin-server-bench.dev . --no-action
      - run: opam depext irmin-server-bench --yes --with-doc
      - run: opam install irmin-server irmin-server-bench --deps-only --with-doc --with-test
      - run: opam exec -- dune build

