name: irmin-server

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.12.0
          - 4.11.0
          - 4.09.1
          - 4.08.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: git submodule update --init
      - run: opam pin add irmin-server-types.dev . --no-action
      - run: opam pin add irmin-server.dev . --no-action
      - run: opam pin add irmin-client.dev . --no-action
      - run: opam pin add irmin-server-bench.dev . --no-action
      - run: opam depext irmin-server irmin-server-types irmin-client --yes --with-doc
      - run: opam install irmin-server-types irmin-server irmin-client --deps-only --with-doc --with-test
      - run: opam exec -- dune build -p irmin-server-types,irmin-server,irmin-client
      - run: opam exec -- dune runtest -p irmin-server-types,irmin-server,irmin-client

  build-bench:
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.12.0
          - 4.11.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: git submodule update --init
      - run: opam pin add irmin-server-types.dev . --no-action
      - run: opam pin add irmin-server.dev . --no-action
      - run: opam pin add irmin-client.dev . --no-action
      - run: opam pin add irmin-server-bench.dev . --no-action
      - run: opam depext irmin-server irmin-server-types irmin-client irmin-server-bench --yes --with-doc
      - run: opam install irmin-server-types irmin-server irmin-client irmin-server-bench --deps-only --with-doc --with-test
      - run: opam install ppx_deriving_yojson bentov memtrace benchmark irmin-test.bench
      - run: opam exec -- dune build
